name: Баг
description: Сообщите о баге, чтобы мы могли исправить его и сделать игру лучше!
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что сообщаете о баге!
        **В одном репорте должно быть описание только одной проблемы. Не стоит описывать пачку багов в одном репорте**
        **Корректное название репорта не менее важно, чем описание**
  - type: textarea
    id: description-of-the-problem
    attributes:
      label: 1/4 Подробное описание проблемы
      placeholder: Подробное описание случившейся проблемы
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: 2/4 Что должно было произойти
    validations:
      required: true
  - type: textarea
    id: reality
    attributes:
      label: 3/4 Что произошло на самом деле
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: 4/4 Как повторить
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Дополнительная информация
      placeholder: айди раунда, версия бьёнда, тестмержи, другая полезная информация
