enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

preferAggregateCacheInfo: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.4.1.cjs
