name: Run tests

on:
  push:
    branches:
      - master

env:
  BYOND_MAJOR: 513
  BYOND_MINOR: 1533
  SPACEMAN_DMM_VERSION: suite-1.5
  NODE_VERSION: 12

jobs:
  beforeInstall:
    runs-on: ubuntu-latest
    steps:
      - run: |
          chmod +x -R scripts/
          chmod +x test/run-test.sh
          test/run-test.sh
