name: Run tests

on:
  push:
    branches:
      - master

env:
  BYOND_MAJOR: 513
  BYOND_MINOR: 1533
  SPACEMAN_DMM_VERSION: suite-1.5
  NODE_VERSION: 12

jobs:
  beforeInstall:
    runs-on: ubuntu-latest
    steps:
      - run: 
          chmod +x -R scripts/
          chmod +x test/run-test.sh
          test/run-test.sh

  DreamChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup cache"
        uses: actions/cache@v2
        with:
          path: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Dreamchecker
        run:  scripts/install-spaceman-dmm.sh dreamchecker
      - name: Run Dreamchecker
        run: ~/dreamchecker

  code_and_map_linting:
    runs-on: ubuntu-latest
    
    env: 
      TEST: LINTING
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5'
      - name: "Code and Map Linting"
      - run: ./scripts/build_tgui.sh

  box_station:
    runs-on: ubuntu-latest

    env: 
      TEST: UNIT
      MAP_NAME: "Box Station"
      MAP_META: boxstation

    steps:
      - name: "Unit Tests - Box Station"
      - run:
          ./scripts/install-byond.sh
          source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup

  gamma_station:
    runs-on: ubuntu-latest
    env: 
      TEST: UNIT
      MAP_NAME: "Gamma Station"
      MAP_META: gamma
    steps:
      - name: "Unit Tests - Gamma Station"
      - run:
         ./scripts/install-byond.sh
         source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup

  compile_everything:
    runs-on: ubuntu-latest
  
    env: 
      TEST: COMPILE
    steps:
      - name: "Compile Everything"
      - run:
          ./scripts/install-byond.sh
          source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
