name: Run tests

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

env:
  global:
    BYOND_MAJOR: 513
    BYOND_MINOR: 1533
    NODE_VERSION: 12

run: chmod +x -R scripts/
run: chmod +x test/run-test.sh

run: test/run-test.sh

jobs:
  DreamChecker:
    runs-on: ubuntu-latest
    
    steps:
      - name: "DreamChecker"
        env: SPACEMAN_DMM_VERSION=suite-1.5
        cache:
          directories: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
        install:
          - ./scripts/install-spaceman-dmm.sh dreamchecker
        run: ~/dreamchecker

  code_and_map_linting:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Code and Map Linting"
      env: 
        TEST: LINTING
      python-version: 3.5
      run: ./scripts/build_tgui.sh

  box_station:
    runs-on: ubuntu-latest
    - name: "Unit Tests - Box Station"
    steps:
      env: 
        TEST: UNIT
        MAP_NAME: "Box Station"
        MAP_META: boxstation
      install:
        - ./scripts/install-byond.sh
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup

  gamma_station:
    - name: "Unit Tests - Gamma Station"
      env: 
        - TEST=UNIT
        - MAP_NAME="Gamma Station"
        - MAP_META=gamma
      install:
        - ./scripts/install-byond.sh
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup

  compile_everything:
    - name: "Compile Everything"
      env: TEST=COMPILE
      install:
        - ./scripts/install-byond.sh
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
