name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BYOND_MAJOR: 513
  BYOND_MINOR: 1533
  SPACEMAN_DMM_VERSION: suite-1.5

jobs:
  DreamChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Dreamchecker
        run:  bash scripts/install-spaceman-dmm.sh dreamchecker
      - name: Run Dreamchecker
        run: ~/dreamchecker
  Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: sudo apt-get install -y uchardet
      - name: Run Tests
        run: bash test/run-test.sh      
