name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BYOND_MAJOR: 513
  BYOND_MINOR: 1533
  SPACEMAN_DMM_VERSION: suite-1.5

jobs:
  DreamChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Dreamchecker
        run:  bash scripts/install-spaceman-dmm.sh dreamchecker
      - name: Run Dreamchecker
        run: ~/dreamchecker
  Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Code and Map Linting
        env: 
          TEST: LINTING
          NODE_VERSION: 12
        run: |
          bash test/run-test.sh
          bash scripts/build_tgui.sh

  Maps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        map_meta: [ boxstation, gamma]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Unit Tests
        env:
          TEST: UNIT
          MAP_META: ${{ matrix.map_meta }}
        run: bash test/run-test.sh

  compile_everything:
    name: "Compile Everything"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: "Compile Everything"
        env: 
          TEST: COMPILE
        run: bash test/run-test.sh
